# Generated by Django 3.2.6 on 2021-08-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('QB', models.IntegerField()),
                ('RB', models.IntegerField()),
                ('WR', models.IntegerField()),
                ('TE', models.IntegerField()),
                ('DEF', models.IntegerField()),
                ('K', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drafter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('draft_type', models.CharField(max_length=255)),
                ('number_of_teams', models.IntegerField()),
                ('scoring', models.CharField(max_length=255)),
                ('drafter', models.ManyToManyField(to='draft_kit_app.Drafter')),
                ('team_composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_composition', to='draft_kit_app.composition')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_league', to='draft_kit_app.league')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_drafter', to='draft_kit_app.drafter')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_league', to='draft_kit_app.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stats', models.IntegerField()),
                ('height', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='draft_kit_app.team')),
            ],
        ),
    ]
