# Generated by Django 3.2.6 on 2021-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_kit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='drafter',
        ),
        migrations.AddField(
            model_name='team',
            name='draft_position',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
